baseURL = 'https://www.lifecoach4u.nl/'
#baseURL = 'https://thethoughtless.github.io/Lifecoach4u-site'

title = 'Lifecoach4u'
theme = 'beautifulhugo'
locale = 'nl-NL'
defaultContentLanguage = "nl"
enableRobotsTXT = true
canonifyURLs = true
disableKinds = ["taxonomy"]
math=false

[caches.images]
    dir = ':cacheDir/images'
 [caches.getresource]
    dir = ":cacheDir/:project"
    maxAge = "1h"       # Opties: "10m", "24h", "0s" (uitzetten), of "-1" (nooit verlopen)
[caches.assets]
    dir = ":cacheDir/assets"
    maxAge = '48h'
    
[services]
  [services.googleAnalytics]
    id = 'G-9PTWJ10NPR'
[minify]
  minifyOutput = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.renderHooks.image]
    useEmbedded = 'fallback'

# Map both the standard assets folder and your static folder into Hugo's asset pipeline
[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "static"
  target = "assets/static"

[module.hugoVersion]
      
[Params]
  toc = false
  math = false
  subtitle = 'persoonlijke coaching in de Krimpenerwaard'
  description='Wil jij werk- of levensvragen aanpakken? Bijvoorbeeld omdat je wilt groeien of steeds tegen dezelfde problemen aan loopt? Dan ben je hier op de goede plek. Persoonlijke coaching kan je verder helpen.'
  logo = '/images/Selfie1.webp'
  showPageDates = false
  hideAuthor = true
  hidePostDates = true
  relativeURLs = true
  

  [Params.author]
      name = "Johan Verrips"

[[Params.bigimg]]
  src='/images/polder.webp'
  desc = "De weg door het leven"
  headerImgStyle = "narrow"


[[menus.main]]
  name = "Wat is coaching?"
  url = "/wat is coaching"
  weight = 1
[[menus.main]]
  name = "Wie ben ik?"
  url = "/wie ben ik"
  weight = 2
[[menus.main]]
  name = "Mijn aanpak"
  url = "/mijn aanpak"
  weight = 3
[[menus.main]]
  name = "Referenties"
  url = "/referenties"
  weight = 3

[[menus.main]]
  name = "Contact"
  url = "/contact"
  weight = 4
[[menus.main]]
  name = "Tips en Tools"
  url = "/tips en tools"
  weight = 5





